repository:
    path: github.com/ickymettle/netgear_cm_exporter
build:
    binaries:
        - name: netgear_cm_exporter
    flags: -mod=vendor -a
    ldflags: |
        -X main.version={{.Version}}
        -X main.revision={{.Revision}}
        -X main.branch={{.Branch}}
        -X main.buildUser={{user}}@{{host}}
        -X main.buildDate={{date "20060102-15:04:05"}}
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
tarball:
    files:
        - README.md
        - LICENSE
