version: 2.1

executors:
  golang:
    docker:
    - image: circleci/golang:1.11

jobs:
  test:
    executor: golang
    steps:
      - checkout
      - run: make prereq
      - run: make ci

workflows:
  version: 2
  netgear_cm_exporter:
    jobs:
    - test
