{
 "title": "Netgear Cable Modem",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DS Power (avg)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netgear_cm_downstream_channel_power_dbmv > 0)"
    }
   ]
  },
  {
   "title": "DS SnR (avg)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netgear_cm_downstream_channel_snr_db > 0)"
    }
   ]
  },
  {
   "title": "DS Corr. Errs (1d)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(netgear_cm_downstream_channel_correctable_errors_total[1d]))"
    }
   ]
  },
  {
   "title": "DS Uncorr. Errs (1d)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(netgear_cm_downstream_channel_uncorrectable_errors_total[1d]))"
    }
   ]
  },
  {
   "title": "DS Locked Chans.",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(netgear_cm_downstream_channel_power_dbmv{lock_status=\"Locked\"})"
    }
   ]
  },
  {
   "title": "US Power (avg)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netgear_cm_upstream_channel_power_dbmv > 0)"
    }
   ]
  },
  {
   "title": "US Symbol Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(netgear_cm_upstream_channel_symbol_rate > 0)"
    }
   ]
  },
  {
   "title": "US Locked Chans.",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(netgear_cm_upstream_channel_power_dbmv{lock_status=\"Locked\"})"
    }
   ]
  },
  { "title": "Downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Downstream Power (dBmV)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netgear_cm_downstream_channel_power_dbmv > 0",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream SnR (dB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "netgear_cm_downstream_channel_snr_db > 0",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream Locked Channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(netgear_cm_downstream_channel_snr_db{lock_status=\"Locked\"})"
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Upstream Power (dBmV)",
   "type": "graph",
   "description": "+7 -> -7 = good range",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netgear_cm_upstream_channel_power_dbmv > 0",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Upstream Symbol Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "netgear_cm_upstream_channel_symbol_rate > 0",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Upstream Locked Channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(netgear_cm_upstream_channel_power_dbmv{lock_status=\"Locked\"})"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Downstream Correctable Errs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(netgear_cm_downstream_channel_correctable_errors_total[5m])",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream Uncorrectable Errs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(netgear_cm_downstream_channel_uncorrectable_errors_total[5m])",
     "legendFormat": "{{frequency}}"
    }
   ]
  }
 ]
}